### ISSUE TITLE
There should be an option to disable status effects in inventory

### ISSUE THREAD

**Issue by FewerFlaws** [semper-idem/huddons-sep#2]
Status effects in the inventory screen don't match the style of the modded HUD.  Nor do they provide extra information.  They should be disabled by default with this mod installed.

It might be worth it to set a few modes for the inventory screen:
  1. Modded GUI visible
  2. Vanilla GUI visible
  3. No status effects visible.

**Comment by semper-idem** [comment]
Good idea, I'll add that once I'm back home.

**Comment by FewerFlaws** [comment]
I appreciate that =D

**Comment by FewerFlaws** [comment]
Works perfectly <3
